{{- if .Values.prometheus.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "metallb.fullname" . }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
spec:
  groups:
  - name: {{ template "metallb.fullname" . }}.rules
    rules:
    {{- if .Values.prometheus.prometheusRule.staleConfig.enabled }}
    - alert: MetalLBStaleConfig
      annotations:
        message: {{`'{{ $labels.job }} - MetalLB {{ $labels.container }} on {{ $labels.pod
          }} has a stale config for > 1 minute'`}}
      expr: metallb_k8s_client_config_stale_bool{job="{{ include "metallb.name" . }}"} == 1
      for: 1m
      {{- with .Values.prometheus.prometheusRule.staleConfig.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.prometheus.prometheusRule.configNotLoaded.enabled }}
    - alert: MetalLBConfigNotLoaded
      annotations:
        message: {{`'{{ $labels.job }} - MetalLB {{ $labels.container }} on {{ $labels.pod
          }} has not loaded for > 1 minute'`}}
      expr: metallb_k8s_client_config_loaded_bool{job="{{ include "metallb.name" . }}"} == 0
      for: 1m
      {{- with .Values.prometheus.prometheusRule.configNotLoaded.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }} 
